TEXT_GAMEOVER  = "FELICITARI!\n\n ATI CASTIGAT!";
TEXT_LOSE = "IMI PARE RAU, JUCATORUL ";
TEXT_LOSE2 = " A CÂSTIGAT ACEST JOC";
TEXT_SCORE     = "SCORUL DVS.";
TEXT_RESTART   = "REPORNIRE";
TEXT_MOVES      = "MUTARI";
TEXT_ARE_SURE = "SUNTETI SIGUR?";
TEXT_SELECT_PLAYERS = "ALEGETI NUMARUL DE JUCATORI!";
TEXT_SELECT_COLOR = "SELECTATI O CULOARE ";
TEXT_TUTORIAL1 = "SALUTARE!\n\n ACEST JOC ESTE ASEMANATOR CU UNO!";
TEXT_TUTORIAL2 = "CARTILE DE ACTIUNE VOR CONDIMENTA JOCUL!\n\nDRAW TWO FORTEAZA JUCATORUL URMATOR SA IA 2 CARTI";
TEXT_TUTORIAL3 = "SKIP CARD OPRESTE JUCATORUL URMATOR SA DECARTEZE";
TEXT_TUTORIAL4 = "REVERSE CARD SCHIMBA SENSUL DE JOC";
TEXT_TUTORIAL5 = "WILD CARD-UL POATE FI PLASAT PE ORICE CARTE ÎN ORICE MOMENT SI VA PERMITE SA SCHIMBATI CULOAREA PENTRU A JUCA ";
TEXT_TUTORIAL6 = "WILD DRAW FOUR ESTE O CARTE CARE VA PERMITE SA SCHIMBATI CULOAREA SI FORTEAZA URMATORUL JUCATOR SA PRIMEASCA 4 CARTI. PENTRU A UTILIZA ACEASTA CARTE, NU TREBUIE SA AVETI ALTE CARTI CARE POT FI JUCATE";
TEXT_TUTORIAL7 = "NU UITATI SA APASATI BUTONUL 1 ATUNCI CÂND MAI AVETI DOAR O CARTE ÎN MÂNA SAU VETI PRIMI CA PENALIZARE ÎNCA 2 CARTI!";
TEXT_PLAYER_1 = "DVS. ";
TEXT_PLAYER_2 = "JUCATOR 2";
TEXT_PLAYER_3 = "JUCATOR 3";
TEXT_PLAYER_4 = "JUCATOR 4";
TEXT_ALERT_1 = "ATI UITAT SA APASATI BUTONUL 1 CÂND MAI AVETI O CARTE ÎN MÂNA. ATI PRIMIT 2 CARTI PENALIZARE";
var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_DEVELOPED = "CREAT DE";


TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Felicitari!";
TEXT_SHARE_MSG1 = "Ati acumulat <strong>";
TEXT_SHARE_MSG2 = " puncte</strong>!<br><br>Dati un share pe Facebook!";
TEXT_SHARE_SHARE1 = "Scorul meu este de ";
TEXT_SHARE_SHARE2 = " puncte! Poti sa faci mai mult ca mine?";

